### ISSUE TITLE
服务器端的启动命令是？

### ISSUE THREAD

**Issue by briteming** [21paradox/node-spdy-proxy-example#1]
服务器端的启动命令是node server.js还是node proxy.js还是node index.js?

**Comment by 21paradox** [comment]
服务端 node index.js ，proxy.js server.js没用了
客户端参照readme设置chrome就行
这只是一个demo项目

**Comment by briteming** [comment]
hi.
服务器上。
root@umh:~/node-spdy-proxy-example-by-21paradox# nohup node index.js > /dev/null &
[1] 10482
root@umh:~/node-spdy-proxy-example-by-21paradox# nohup: ignoring input and redirecting stderr to stdout

root@umh:~/node-spdy-proxy-example-by-21paradox# 
root@umh:~/node-spdy-proxy-example-by-21paradox# lsof -i:5443
COMMAND   PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
node    10482 root   10u  IPv6 889226813      0t0  TCP *:5443 (LISTEN)
root@umh:~/node-spdy-proxy-example-by-21paradox# ps aux|grep index.js
root     10482  0.6  1.2 892700 26576 pts/1    Sl   10:34   0:00 node index.js
root     10492  0.0  0.0  11072   836 pts/1    S+   10:35   0:00 grep index.js
root@umh:~/node-spdy-proxy-example-by-21paradox# ls
README.md	     index.js			  package.json
config.example.json  node-spdy-proxy-example.pac  proxy.js
config.json	     node_modules		  server.js
root@umh:~/node-spdy-proxy-example-by-21paradox#

只是客户端未搞定。一定要带参数“--use-spdy=npn”启动chrome吗？？我仅是在chrome里设置了switchyomega的pac情景模式，但是翻#墙失败

**Comment by briteming** [comment]
试过了。先带参数“--use-spdy=npn”启动chrome，然后在chrome里设置switchyomega的pac情景模式，但是翻#墙仍然失败。如何解决？

**Comment by 21paradox** [comment]
这个项目只是为了尝试chrome的spdy方式连接。写的比较潦草，不推荐使用。
服务端需要： 一个域名、https证书
客户端: chrome打开spdy模式  

如果要无负担使用的话 推荐你看看 https://github.com/21paradox/node-webproxy 
用法和 sh*****s-he***ku 一样，但是 **性能和稳定性** 提升很多。
